config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: { sessions: 'sessions', registrations:'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show, :edit, :update]
  resources :teams, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    get '/team_answers', to: 'teams#team_answers'
    resources :challenges, only: [:index, :show, :edit, :update] do
      resources :answers
    end
    resources :members, only: [:new, :create, :destroy]
    end
  resources :cities, only: [:index, :show] do
    get 'weather', as: :members
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook]

  mount_uploader :profile_picture, PhotoUploader

  has_many :members
  has_many :teams, through: :members

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true

  def self.find_for_facebook_oauth(auth)
    user_params = auth.to_h.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)

    user = User.where(provider: auth.provider, uid: auth.uid).first
    user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end

  def user_score
    #find every teams for one user
    #
    list_teams = self.teams
      user_score = 0
    list_teams.each do |team|
      user_score += team.score
    end
    user_score
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in (@user)
      redirect_to user_path(current_user), notice: 'Signed in successfully.'
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?

    else

 session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    authorize @user

  end

  def edit
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
    authorize @user
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :id, :address, :profile_picture)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_card.html.erb
<div class="row">
  <% if member.team.end_date.to_date > Date.today %>
    <div class="col-xs-10 left-card text-left">
  <% else %>
    <div class="col-xs-10 left-card-outdate text-left">
  <% end %>
    <div class="row">
      <div class="col-xs-4">
        <div class="avatar-link">
          <% if member.team.team_picture.present? %>
            <%= cl_image_tag member.team.team_picture, class: "picture-card" %>
          <% else %>
            <%= cl_image_tag("default_fkhyps.png", class: "picture-card") %>
          <% end %>
        </div>
      </div>
      <div class="col-xs-8">
        <p><%= member.team.city.name.upcase %></p>
        <h2><%= member.team.title %></h2>
        <p><%= member.team.score %> <sup>PT</sup></p>
      </div>
    </div>
      <% if policy(member.team).show? %>
        <%= link_to "", team_path(member.team.id), class: "card-link" %>
      <% end %>
    </div>
    <% if member.team.end_date.to_date > Date.today %>
      <div class="col-xs-2 delete-card text-center">
    <% else %>
      <div class="col-xs-2 delete-card-outdate text-center">
    <% end %>
      <% if policy(member.team).destroy? %>
        <i class="fa fa-trash" aria-hidden="true"></i>
        <%= link_to "", team_path(member.team), method: :delete, class: "card-link" %>
      <% end %>
    </div>
</div>

app/views/users/edit.html.erb
<div class="container">

  <h3>Edit your profil:</h3>

  <%= simple_form_for @user, url: user_path do |u| %>
    <%= u.input :first_name, placeholder: "Your first name." %>
    <%= u.input :last_name, placeholder: "Your last name." %>
    <%= u.input :address, placeholder: "Your address." %>
    <%= u.input :profile_picture %>
    <%= u.input :profile_picture_cache, as: :hidden %>
    <%= u.submit %>

  <% end %>

  <%= link_to 'Go Back', user_path(@user) %>

</div>
<br>
<br>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-12 text-center">
      <div class="container text-center">
        <div class="profilecard-top">
          <div class="lilspace text-center">
            <% if @user.facebook_picture_url.nil? %>
              <% unless @user.profile_picture.nil?  %>
                <% if @user.profile_picture.present? %>
                  <%= cl_image_tag @user.profile_picture, class: "avatar-user", crop: :fill %>
                <% else %>
                  <%= cl_image_tag("default_fkhyps.png", class: "avatar-user") %>
                <% end %>
              <% end %>
            <%else %>
              <%= image_tag @user.facebook_picture_url, class: "avatar-user", crop: :fill %>
            <% end %>
            <h2><%= @user.first_name %> <%= @user.last_name %> <%= link_to "", edit_user_path(@user),class: "fa fa-pencil edit-button", style: "color: #516DAC;", method: :get %></h2>
            <strong class="point-display"><%= @user.user_score %><sup>PT</sup></strong>
          </div>
        </div>
      </div>
    <h1 class="text-left title-yo" style="color: #516DAC;"><b>MY TEAMS</b></h1>
    <div class="profilecard-bottom text-right">
      <p><%= link_to "CREATE A NEW TEAM", new_team_path, style: "text-decoration: none; color: white;" %></p>
      <% @user.members.each do |member| %>
        <%= render "card", member: member %>
      <% end %>
    </div>
    </div>
  </div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>