config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: { sessions: 'sessions', registrations:'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show, :edit, :update]
  resources :teams, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    get '/team_answers', to: 'teams#team_answers'
    resources :challenges, only: [:index, :show, :edit, :update] do
      resources :answers
    end
    resources :members, only: [:new, :create, :destroy]
    end
  resources :cities, only: [:index, :show] do
    get 'weather', as: :members
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer text-center">
  <ul class="list-inline footer-icons">
    <li><i class="icons fa fa-2x fa-youtube" aria-hidden="true"></i></li>

    <li>
      <a href=https://www.instagram.com/tripin.contact <i class="icons fa fa-2x fa-instagram" aria-hidden="true"></i>
      </a>
    </li>

    <li>
      <a href=https://www.facebook.com/profile.php?id=100014558021234
      <i class="icons fa fa-2x fa-facebook" aria-hidden="true"></i>
     </a>
    </li>

    <li> <a href=https://twitter.com <i class="icons fa fa-2x fa-twitter" aria-hidden="true"></i></a></li>
  </ul>

  <ul class="list-inline footer-text">
    <p>Terms of Use | Privacy Policy | Contact Us | About Us</p>
  </ul>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon <% if controller.controller_name == "pages" && controller.action_name == "home" %>navbar-dark<% end %>">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>

    <% if @navbardark %>
      <%= cl_image_tag("LOGO-WHITE_xhrvre.png", :width=>5000, :crop=>"scale") %>
    <% else %>
      <%= cl_image_tag("LOGO-BLEU_mycjfo.png", :width=>5000, :crop=>"scale")
       %>
    <% end %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>
    <!-- Notification -->
    <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
    <% end %>

    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item nav-left">
      <div class="dropdown">
        <% if current_user.profile_picture.present? %>
        <%= image_tag current_user.profile_picture, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <% else %>
        <%= image_tag("default.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown") %>
        <% end %>

        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to user_path(current_user) do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>

          <% current_user.teams.each do |t| %>
          <li><%= link_to t.title, team_challenges_path(t), method: :get if t.in_trip? %></li>
          <%end%>

          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>


        </ul>
      </div>
    </div>

    <% else %>

    <!-- Login text link -->
    <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>
  </div>

  <% if user_signed_in? %>
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle dropdown-color" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to user_path(current_user) do %><i class="fa fa-user"></i> Profile<% end %></li>
        <% current_user.teams.each do |t| %>
          <li><%= link_to t.title, team_challenges_path(t), method: :get if t.in_trip? %></li>
        <%end%>
        <li><%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %></li>
        </ul>
      </div>
    </div>

  <% else %>
      <div class="navbar-wagon-item hidden-md hidden-lg">
        <div class="dropdown">
          <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
             <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
             </li>
           </ul>
         </div>
       </div>
  <% end %>
</div>