config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: { sessions: 'sessions', registrations:'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show, :edit, :update]
  resources :teams, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    get '/team_answers', to: 'teams#team_answers'
    resources :challenges, only: [:index, :show, :edit, :update] do
      resources :answers
    end
    resources :members, only: [:new, :create, :destroy]
    end
  resources :cities, only: [:index, :show] do
    get 'weather', as: :members
  end
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :user
  belongs_to :team
  attr_accessor :email

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def new
    @team = Team.find(params[:team_id])
    @member = Member.new
    authorize @team
  end

  def create
    @team = Team.find(params[:team_id])
    @user = User.find_by_email(params[:member][:email])
    if @user
      Member.create(user: @user, team: @team)
      flash[:success] = "Member added"
    else
      @email = params[:member][:email]
    end
    authorize @team
    respond_to do |format|
      format.js
      format.html {redirect_to team_path(@team)}
    end
  end

  def destroy
    @member = Member.find(params[:id])
    @team = @member.team
    authorize @team
    @member.destroy
    redirect_to team_path(@team)
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_member.html.erb
<% if user %>
 <li>
   <%= user.email %>, <%= user.first_name %> <%= user.last_name %>, <%= image_tag user.profile_picture, class: "avatar" %>
 </li>
<% elsif email %>
 <li><%= email %>, <i class="fa fa-envelope-o"></i></li>
<% end %>

app/views/members/create.js.erb
member = $('<%= j render("members/member", user: @user, email: @email) %>').hide();
member.appendTo($('.members-list'));
$('#member_email').val('');
member.fadeIn();

app/views/members/destroy.html.erb
<h1>Teams#destroy</h1>
<p>Find me in app/views/teams/destroy.html.erb</p>

app/views/members/new.html.erb
<div class="bigcontainer">

  <%= link_to '', team_path(@team), class: "fa fa-times fa-lg cross-back-back", style: "color: #484846;"%>

  <h2>Add team members</h2>
  <%= simple_form_for @member , url: team_members_path(@team), method: :post, remote: true, defaults: { input_html: { class: 'input-container animation-collor' } } do |f| %>
  <%= f.input :email, placeholder: "Enter the email of your teammate", label: 'Email of your teammate', wrapper: :p_wrapper %>
  <div class="topspace">
    <%= f.button :submit, 'Add member', class: "btn-blue" %>
    <% end %>
  </div>

  <div class="links">
    <div class="liltopspace">
      <ul class="members-list list-unstyled" >
        <li>
          <%#= link_to "", team_member_path(@team, @member), method: :delete, class: "fa fa-trash" %></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="btn-bottom text-center">
    <p><%= link_to 'Create your team', team_path(@team) %></p>
  </div>